### ISSUE TITLE
Doubts regarding the goals for this project

### ISSUE THREAD

**Issue by Kanha-13** [flexivian/flexbench#12]
I gone through the idealist page and have certain doubts regarding the GSOC goals for this project:

- Its mentions to make this a standalone desktop app , but in the second point its mentioned to make this a web server exposing REST APIs these two things I didn't understand clearly
- I didn't understand the OpenIDC thing and Implement a DSL language to describe scenarios that can be executed by flexbench
- Integrate Nginx proxy 
- Implement a DSL language to describe scenarios that can be executed by flexbench (eg. store a scenario under a .flxb file )
- Implement an editor for .flxb files with syntax highlighting support 

Please guide me through this so that I can start with the draft proposal

**Comment by Kanha-13** [comment]
@iskitsas I have submitted my proposal could you please give feedback on it, since tomorrow is the last day.

**Comment by iskitsas** [comment]
@Kanha-13 

I had sent you an email yesterday. Here is some feedback:

I am attaching the proposal submitted last year for another project I was mentoring. It would be good to follow the same pattern. Do not forget to add the sections about yourself and motivation. See below and adopt: 
https://docs.google.com/document/d/1HNCcofmSAk7byMiA216i5Y0Z59o0ifDCFC5nX19Nmec/edit?usp=sharing

Additionally, check here the goals/expected-results based on the size of the project:
https://docs.google.com/document/d/10KyOVv_8gGUHqvm1pXY235ly3YGtNq1J1rjPpCzvUq0/edit?usp=sharing

You can adopt your timelines based on the above.

**Comment by Kanha-13** [comment]
@iskitsas Sorry, but I didn't recieve any email. I have already added the about my self section and motivation section.
