### ISSUE TITLE
Https calls are not supported

### ISSUE THREAD

**Issue by iskitsas** [flexivian/flexbench#18]
Currently, the tool supports only http calls, even if the port is changed to 443. The config erroneously gives the user the impression that https urls could be used, but the core library does not support that, and it will fail. 

Possible workaround:

When 443 port is used, the main lib should use the "https" module instead of "http".

**Comment by Kanha-13** [comment]
Is there any way to find which port is used?

**Comment by iskitsas** [comment]
You can easily check for 443 port, and switch to the node https library where needed. 
Affected areas:

- lib/main.js
- lib/ThrottleProxy/throttleServer.js
- lib/lib-helper.js (maybe)

url to test: www.example.com
port: 443

If you try to just switch to "https" module you will see that the flows are working only with throttle mode disabled (in example use -1). If you enable it, you will get an ssl certificate issue, due to the proxy (couldn't find a way yet to overcome this)

Bottom up:
- Refactor to use the https module when port 443 is used
- Try to make proxy server to work with https requests when throttling is enabled
- Create a new simple-request example to use https

**Comment by Kanha-13** [comment]
`Trottle-Proxy Worker 1
node:_http_client:164
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:372:5)
    at new ClientRequest (node:_http_client:164:11)
    at Object.request (node:https:353:10)
    at Object.request (D:\gsoc\gfoss\flexbench\lib\main.js:411:20)
    at requestFunc (D:\gsoc\gfoss\flexbench\example\simple-request.js:62:32)
    at D:\gsoc\gfoss\flexbench\lib\main.js:335:29
    at Timeout._onTimeout (D:\gsoc\gfoss\flexbench\lib\main.js:377:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ERR_INVALID_PROTOCOL'
}`


Is it the breaking bug ? Have I reproduced it correctly?

**Comment by iskitsas** [comment]
@Kanha-13 yes, you have reproduced it correctly, and you will find one more issue when overcoming this. 

This error is because of the agent from module 'agentkeepalive'

In lib-helper file you will find the init using a default constructor:

```
var keepAliveAgent = new KeepAliveAgent({
     maxSockets: 2000
});
```
which by default is using HttpOptions. So, when https is enabled the initialisation of keepAliveAgent should be something like this I suppose:
```
var keepAliveAgent = new HttpsAgent({
    maxSockets: 2000
});
```
Check the docs of the module to be sure. By adding this you will tackle this error, however you will face the next one:

> error:write EPROTO 4570242560:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 40

**Comment by iskitsas** [comment]
@Kanha-13 after investigating a little further, you do no need to change the the agent.

The throttle proxy will stay in http, we will need just to switch the proxied requests to https, based on what the user has configured. 

So the task is just to include the https module, along with the http, and just switch to https or http, based on the port configuration.

I can add TODO items within the code if need assistance on this, but if it is clear feel free to proceed on your own. I can also provide a patch with the hardcoded changes I did locally, to make it work for https, so you can adopt/refactor accordingly

**Comment by iskitsas** [comment]
[flexbench-playing_with_https.patch.zip](https://github.com/flexivian/flexbench/files/8876820/flexbench-playing_with_https.patch.zip)

**Comment by Kanha-13** [comment]
thank you @iskitsas for this patch you have 99.99% completed the whole work 😅

**Comment by Kanha-13** [comment]
there is one doubt I have it might be very silly if the request function there is an `option` object, that has a `host` as key-value pair, so there why http://example.com not working? But www.example.com works fine!

**Comment by iskitsas** [comment]
> thank you @iskitsas for this patch you have 99.99% completed the whole work 😅

I would say 50% :)

You will need to do some refactoring to support both http and https. However it looks trivial. Ping me on slack if you need more clarifications

**Comment by Kanha-13** [comment]
Ok, sure I will raise my questions on slack.
