### ISSUE TITLE
Basic requirements and UX for flexbench desktop app

### ISSUE THREAD

**Issue by iskitsas** [flexivian/flexbench#22]
1st time opening the app, the user should get a prompt to create a project, under which he will create his test scenarios

Multiple projects can be created, the user should select a project, find all scenarios, select a scenario to edit/run, or create a new scenario

Supported options for a scenario: 

- Set name of scenario
- Total duration
- Number of workers
- Number of clients per worker
- Number of total requests per client
- Throttling per request in bps
- Range of random or fixed delays between requests
- Set list of requests to test
- Run/Stop/Kill scenario
- Save/Delete scenario

**Comment by Kanha-13** [comment]
Hi @iskitsas , can you please explain what is `set list of requests to test`

**Comment by Kanha-13** [comment]
#28
