### ISSUE TITLE
Implement a heavy load scenario

### ISSUE THREAD

**Issue by iskitsas** [flexivian/flexbench#3]
Locate the file [heavy-load.js](https://github.com/flexivian/flexbench/blob/master/example/heavy-load.js) and implement a heavy (http) load scenario using flexbench

**Comment by Kanha-13** [comment]
Could you please guid me how to approach this issue!

**Comment by iskitsas** [comment]
> Could you please guid me how to approach this issue!

Review the examples to get grasp on how this package can be used to generate requests, and implement a scenario with multiple clients "consuming" video streams.

For example, you could simulate the case where you have 100 clients watching a video stream

**Comment by Kanha-13** [comment]
Is there any configuration, to set the total chunk size I am requesting for?

**Comment by AnshumanPadiya** [comment]
@iskitsas Hey there, if this issue is still active can I try working on it?

**Comment by kavyarishi19** [comment]
assign me this issue
