### ISSUE TITLE
Implement a stream manipulation scenario

### ISSUE THREAD

**Issue by iskitsas** [flexivian/flexbench#4]
Locate the file [manipulate_stream.js](https://github.com/flexivian/flexbench/blob/master/example/manipulate_stream.js) and implement a stream manipulation scenario (eg. simulate the scenario of watching a youtube video) using flexbench

**Comment by Kanha-13** [comment]
could you please elaborate manipulate stream, like what needs to be modify in the request function!

**Comment by iskitsas** [comment]
Reading chunks from a video. Eg. simulate the scenario where a user moves the timeline slider in a video player

**Comment by Kanha-13** [comment]
ok thank you for the reply

**Comment by Kanha-13** [comment]
I was trying to implement this, but got stuck with terminating the runTest function

with the below function in was trying to stop runTest when the starting length exceeds the total content length 

  setInterval(() => {
          if (range_start_from > total_content_length) {
              trafficSimulator.stop();
          }
      }, 1100);

**Comment by Kanha-13** [comment]
@iskitsas  could you please help me with this!

**Comment by iskitsas** [comment]
@Kanha-13 it might be an issue with the library. Can you please validate that it is a bug, write down the exact steps to reproduce and open an issue?

**Comment by Kanha-13** [comment]
actually I debug this in main.js and found that when any condition is applied inside setInterval or setTimeout then the request is made by the workers not the master but if no conditions are applied inside setTimeOut or interval then the request is made by master.

Since at line 123 of main.js it validates whether its master or worker and here it fails

`main.js`

    function stop(){
        if(cluster.isMaster){
            //send stop message to all workers
            eachWorker(function(worker) {
                gh.consola.basic(util.format('Master sending stop signal to Worker[%s]',worker.id));
                worker.send({ stopExecution: 'true' });//Master asks workers to stop execution
            });
        }
    }

**Comment by Kanha-13** [comment]
to reproduce this issue 

`runTest function `

       function runTest() {
        trafficSimulator.debugMode(true);
        trafficSimulator.testDuration(-1);//-1 for infinite run
        trafficSimulator.workers(4);
        trafficSimulator.clients(2)
        trafficSimulator.throttleRequests_bps(50000);//-1 for no throttling
        trafficSimulator.randomDelayBetweenRequests('0.5-1.1');
        trafficSimulator.setFunc('request', requestFunc);
    
        trafficSimulator.start();
    
        trafficSimulator.events.on('end', function (stats) {
            //This function will run on exit/stop, when worker has received a message to offload his stats to his master
            //Get from stats object all exposed metrics
            console.log('Traffic Simulator Results');
            console.log('-------------------------');
    
            var cArr = Object.keys(stats.counters);
    
            for (var i = 0; i < cArr.length; i++) {
                var key = cArr[i];
                console.log('counter %s: %s ', key, stats.counters[key]);
            }
            console.log("Exiting..");
            process.exit();
        })
    
    
    
        //stop test after specific period or condition\
        setInterval(() => {
            if (range_start_from > total_content_length) {
                trafficSimulator.stop();
            }
        }, 1100);
    }
